import fs from 'node:fs';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  actionsCommand,
  generateWorkflow,
  validateWorkflowYaml,
} from '../../src/commands/actions-cmd.js';
import { defaultContext } from '../../src/util/completion.js';

let tmpDir: string;
const tmpRoot = path.join(process.cwd(), '.vitest-actions-cmd-tmp');

beforeEach(() => {
  fs.mkdirSync(tmpRoot, { recursive: true });
  tmpDir = fs.mkdtempSync(path.join(tmpRoot, 'case-'));
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
  fs.rmSync(tmpRoot, { recursive: true, force: true });
});

describe('generateWorkflow', () => {
  it('builds a CI workflow with comments and valid structure', () => {
    const yaml = generateWorkflow('ci build and test on push and pull request');

    expect(yaml).toContain('# Generated by iCopilot /actions');
    expect(yaml).toContain('name:');
    expect(yaml).toContain('on:');
    expect(yaml).toContain('push:');
    expect(yaml).toContain('pull_request:');
    expect(yaml).toContain('jobs:');
    expect(yaml).toContain('npm test --if-present');
    expect(validateWorkflowYaml(yaml)).toEqual([]);
  });

  it('merges lint and security templates when the description asks for both', () => {
    const yaml = generateWorkflow(
      'lint, prettier, and security dependency audit for pull requests',
    );

    expect(yaml).toContain('Run ESLint');
    expect(yaml).toContain('Check formatting');
    expect(yaml).toContain('Run npm audit');
    expect(yaml).toContain('schedule:');
    expect(validateWorkflowYaml(yaml)).toEqual([]);
  });

  it('includes semantic-release automation when requested', () => {
    const yaml = generateWorkflow('automated release automation with semantic-release on main');

    expect(yaml).toContain('workflow_dispatch:');
    expect(yaml).toContain('Run semantic-release');
    expect(yaml).toContain("GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'");
    expect(validateWorkflowYaml(yaml)).toEqual([]);
  });
});

describe('actionsCommand', () => {
  it('lists workflow files in .github/workflows', () => {
    const workflowDir = path.join(tmpDir, '.github', 'workflows');
    fs.mkdirSync(workflowDir, { recursive: true });
    fs.writeFileSync(
      path.join(workflowDir, 'ci.yml'),
      generateWorkflow('ci build and test'),
      'utf8',
    );
    fs.writeFileSync(
      path.join(workflowDir, 'lint.yaml'),
      generateWorkflow('lint and prettier checks'),
      'utf8',
    );

    const output = actionsCommand(['list'], tmpDir);

    expect(output).toContain('Existing workflows');
    expect(output).toContain('ci.yml');
    expect(output).toContain('lint.yaml');
  });

  it('validates workflow files and reports invalid YAML heuristics', () => {
    const workflowDir = path.join(tmpDir, '.github', 'workflows');
    fs.mkdirSync(workflowDir, { recursive: true });
    fs.writeFileSync(
      path.join(workflowDir, 'valid.yml'),
      generateWorkflow('ci build and test'),
      'utf8',
    );
    fs.writeFileSync(
      path.join(workflowDir, 'broken.yml'),
      ['name: Broken workflow', 'jobs:', '  build:', '    runs-on: ubuntu-latest'].join('\n'),
      'utf8',
    );

    const output = actionsCommand(['validate'], tmpDir);

    expect(output).toContain('Workflow validation');
    expect(output).toContain('valid valid.yml');
    expect(output).toContain('invalid broken.yml');
    expect(output).toContain('missing top-level "on" trigger block');
    expect(output).toContain('job "build" is missing "steps"');
  });

  it('renders generated YAML for free-form descriptions', () => {
    const output = actionsCommand(['deploy', 'on', 'tags', 'with', 'semantic-release'], tmpDir);

    expect(output).toContain('Generated workflow');
    expect(output).toContain('.github/workflows/');
    expect(output).toContain('semantic-release');
  });
});

describe('actions slash wiring', () => {
  it('wires /actions into slash handling and help text', () => {
    const slashSource = fs.readFileSync(
      path.join(process.cwd(), 'src', 'commands', 'slash.ts'),
      'utf8',
    );

    expect(slashSource).toContain("import { actionsCommand } from './actions-cmd.js';");
    expect(slashSource).toContain('/actions <desc>|list|validate');
    expect(slashSource).toContain("case 'actions':");
    expect(slashSource).toContain('actionsCommand(rest, s.state.cwd)');
  });

  it('adds /actions to shell completion context', () => {
    expect(defaultContext().slashCommands).toContain('actions');
  });
});
